import type { AppCategory, InstalledApp } from '@/constants/types';

export const AppCategories: { id: AppCategory | 'all'; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'social', label: 'Social' },
  { id: 'entertainment', label: 'Entertainment' },
  { id: 'games', label: 'Games' },
  { id: 'communication', label: 'Communication' },
  { id: 'shopping', label: 'Shopping' },
  { id: 'productivity', label: 'Productivity' },
  { id: 'utilities', label: 'Utilities' },
];

/** Stand-in for the device's installed app list until the native module exists. */
export const MockInstalledApps: InstalledApp[] = [
  { id: 'com.instagram.android', name: 'Instagram', category: 'social', icon: 'logo-instagram', color: '#E1306C' },
  { id: 'com.facebook.katana', name: 'Facebook', category: 'social', icon: 'logo-facebook', color: '#1877F2' },
  { id: 'com.zhiliaoapp.musically', name: 'TikTok', category: 'social', icon: 'logo-tiktok', color: '#111111' },
  { id: 'com.twitter.android', name: 'X', category: 'social', icon: 'logo-x', color: '#111111' },
  { id: 'com.snapchat.android', name: 'Snapchat', category: 'social', icon: 'logo-snapchat', color: '#F7C600' },
  { id: 'com.reddit.frontpage', name: 'Reddit', category: 'social', icon: 'logo-reddit', color: '#FF4500' },
  { id: 'com.pinterest', name: 'Pinterest', category: 'social', icon: 'logo-pinterest', color: '#E60023' },
  { id: 'com.linkedin.android', name: 'LinkedIn', category: 'social', icon: 'logo-linkedin', color: '#0A66C2' },
  { id: 'com.instagram.barcelona', name: 'Threads', category: 'social', icon: 'logo-threads', color: '#222222' },
  { id: 'com.google.android.youtube', name: 'YouTube', category: 'entertainment', icon: 'logo-youtube', color: '#FF0000' },
  { id: 'com.netflix.mediaclient', name: 'Netflix', category: 'entertainment', icon: 'film', color: '#E50914' },
  { id: 'com.spotify.music', name: 'Spotify', category: 'entertainment', icon: 'musical-notes', color: '#1DB954' },
  { id: 'tv.twitch.android.app', name: 'Twitch', category: 'entertainment', icon: 'logo-twitch', color: '#9146FF' },
  { id: 'com.tencent.ig', name: 'PUBG Mobile', category: 'games', icon: 'game-controller', color: '#F2A900' },
  { id: 'com.dts.freefireth', name: 'Free Fire', category: 'games', icon: 'flame', color: '#FF6A00' },
  { id: 'com.supercell.clashofclans', name: 'Clash of Clans', category: 'games', icon: 'game-controller', color: '#3C8D2F' },
  { id: 'com.king.candycrushsaga', name: 'Candy Crush', category: 'games', icon: 'game-controller', color: '#EA4C89' },
  { id: 'com.valvesoftware.android.steam.community', name: 'Steam', category: 'games', icon: 'logo-steam', color: '#1B2838' },
  { id: 'com.whatsapp', name: 'WhatsApp', category: 'communication', icon: 'logo-whatsapp', color: '#25D366' },
  { id: 'com.facebook.orca', name: 'Messenger', category: 'communication', icon: 'chatbubble-ellipses', color: '#0084FF' },
  { id: 'org.telegram.messenger', name: 'Telegram', category: 'communication', icon: 'paper-plane', color: '#229ED9' },
  { id: 'com.discord', name: 'Discord', category: 'communication', icon: 'logo-discord', color: '#5865F2' },
  { id: 'com.google.android.gm', name: 'Gmail', category: 'communication', icon: 'mail', color: '#EA4335' },
  { id: 'com.daraz.android', name: 'Daraz', category: 'shopping', icon: 'cart', color: '#F57224' },
  { id: 'com.amazon.mShop.android.shopping', name: 'Amazon', category: 'shopping', icon: 'logo-amazon', color: '#FF9900' },
  { id: 'com.bKash.customerapp', name: 'bKash', category: 'shopping', icon: 'wallet', color: '#E2136E' },
  { id: 'com.pathao.user', name: 'Pathao', category: 'utilities', icon: 'bicycle', color: '#E4002B' },
  { id: 'com.android.chrome', name: 'Chrome', category: 'productivity', icon: 'logo-chrome', color: '#4285F4' },
  { id: 'com.google.android.apps.maps', name: 'Maps', category: 'utilities', icon: 'map', color: '#34A853' },
  { id: 'com.google.android.apps.docs', name: 'Google Drive', category: 'productivity', icon: 'logo-google', color: '#4285F4' },
  { id: 'com.medium.reader', name: 'Medium', category: 'productivity', icon: 'logo-medium', color: '#111111' },
  { id: 'com.android.camera', name: 'Camera', category: 'utilities', icon: 'camera', color: '#607D8B' },
  { id: 'com.android.calculator2', name: 'Calculator', category: 'utilities', icon: 'calculator', color: '#FF9500' },
  { id: 'com.google.android.apps.magazines', name: 'News', category: 'productivity', icon: 'newspaper', color: '#4285F4' },
];
